// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AlgorithmConfig_conf.proto

#ifndef PROTOBUF_INCLUDED_AlgorithmConfig_5fconf_2eproto
#define PROTOBUF_INCLUDED_AlgorithmConfig_5fconf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_AlgorithmConfig_5fconf_2eproto 

namespace protobuf_AlgorithmConfig_5fconf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_AlgorithmConfig_5fconf_2eproto
namespace common {
class ModuleConfig;
class ModuleConfigDefaultTypeInternal;
extern ModuleConfigDefaultTypeInternal _ModuleConfig_default_instance_;
class ModulesConfig;
class ModulesConfigDefaultTypeInternal;
extern ModulesConfigDefaultTypeInternal _ModulesConfig_default_instance_;
}  // namespace common
namespace google {
namespace protobuf {
template<> ::common::ModuleConfig* Arena::CreateMaybeMessage<::common::ModuleConfig>(Arena*);
template<> ::common::ModulesConfig* Arena::CreateMaybeMessage<::common::ModulesConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace common {

// ===================================================================

class ModuleConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.ModuleConfig) */ {
 public:
  ModuleConfig();
  virtual ~ModuleConfig();

  ModuleConfig(const ModuleConfig& from);

  inline ModuleConfig& operator=(const ModuleConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ModuleConfig(ModuleConfig&& from) noexcept
    : ModuleConfig() {
    *this = ::std::move(from);
  }

  inline ModuleConfig& operator=(ModuleConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ModuleConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModuleConfig* internal_default_instance() {
    return reinterpret_cast<const ModuleConfig*>(
               &_ModuleConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(ModuleConfig* other);
  friend void swap(ModuleConfig& a, ModuleConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModuleConfig* New() const final {
    return CreateMaybeMessage<ModuleConfig>(NULL);
  }

  ModuleConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ModuleConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ModuleConfig& from);
  void MergeFrom(const ModuleConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModuleConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  const ::std::string& type() const;
  void set_type(const ::std::string& value);
  #if LANG_CXX11
  void set_type(::std::string&& value);
  #endif
  void set_type(const char* value);
  void set_type(const char* value, size_t size);
  ::std::string* mutable_type();
  ::std::string* release_type();
  void set_allocated_type(::std::string* type);

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // @@protoc_insertion_point(class_scope:common.ModuleConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr type_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AlgorithmConfig_5fconf_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class ModulesConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:common.ModulesConfig) */ {
 public:
  ModulesConfig();
  virtual ~ModulesConfig();

  ModulesConfig(const ModulesConfig& from);

  inline ModulesConfig& operator=(const ModulesConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  ModulesConfig(ModulesConfig&& from) noexcept
    : ModulesConfig() {
    *this = ::std::move(from);
  }

  inline ModulesConfig& operator=(ModulesConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const ModulesConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ModulesConfig* internal_default_instance() {
    return reinterpret_cast<const ModulesConfig*>(
               &_ModulesConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(ModulesConfig* other);
  friend void swap(ModulesConfig& a, ModulesConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline ModulesConfig* New() const final {
    return CreateMaybeMessage<ModulesConfig>(NULL);
  }

  ModulesConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<ModulesConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const ModulesConfig& from);
  void MergeFrom(const ModulesConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ModulesConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .common.ModuleConfig modules = 1;
  int modules_size() const;
  void clear_modules();
  static const int kModulesFieldNumber = 1;
  ::common::ModuleConfig* mutable_modules(int index);
  ::google::protobuf::RepeatedPtrField< ::common::ModuleConfig >*
      mutable_modules();
  const ::common::ModuleConfig& modules(int index) const;
  ::common::ModuleConfig* add_modules();
  const ::google::protobuf::RepeatedPtrField< ::common::ModuleConfig >&
      modules() const;

  // @@protoc_insertion_point(class_scope:common.ModulesConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::common::ModuleConfig > modules_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_AlgorithmConfig_5fconf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ModuleConfig

// string type = 1;
inline void ModuleConfig::clear_type() {
  type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ModuleConfig::type() const {
  // @@protoc_insertion_point(field_get:common.ModuleConfig.type)
  return type_.GetNoArena();
}
inline void ModuleConfig::set_type(const ::std::string& value) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.ModuleConfig.type)
}
#if LANG_CXX11
inline void ModuleConfig::set_type(::std::string&& value) {
  
  type_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.ModuleConfig.type)
}
#endif
inline void ModuleConfig::set_type(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.ModuleConfig.type)
}
inline void ModuleConfig::set_type(const char* value, size_t size) {
  
  type_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.ModuleConfig.type)
}
inline ::std::string* ModuleConfig::mutable_type() {
  
  // @@protoc_insertion_point(field_mutable:common.ModuleConfig.type)
  return type_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModuleConfig::release_type() {
  // @@protoc_insertion_point(field_release:common.ModuleConfig.type)
  
  return type_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModuleConfig::set_allocated_type(::std::string* type) {
  if (type != NULL) {
    
  } else {
    
  }
  type_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), type);
  // @@protoc_insertion_point(field_set_allocated:common.ModuleConfig.type)
}

// string name = 2;
inline void ModuleConfig::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& ModuleConfig::name() const {
  // @@protoc_insertion_point(field_get:common.ModuleConfig.name)
  return name_.GetNoArena();
}
inline void ModuleConfig::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:common.ModuleConfig.name)
}
#if LANG_CXX11
inline void ModuleConfig::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:common.ModuleConfig.name)
}
#endif
inline void ModuleConfig::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:common.ModuleConfig.name)
}
inline void ModuleConfig::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:common.ModuleConfig.name)
}
inline ::std::string* ModuleConfig::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:common.ModuleConfig.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ModuleConfig::release_name() {
  // @@protoc_insertion_point(field_release:common.ModuleConfig.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ModuleConfig::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:common.ModuleConfig.name)
}

// -------------------------------------------------------------------

// ModulesConfig

// repeated .common.ModuleConfig modules = 1;
inline int ModulesConfig::modules_size() const {
  return modules_.size();
}
inline void ModulesConfig::clear_modules() {
  modules_.Clear();
}
inline ::common::ModuleConfig* ModulesConfig::mutable_modules(int index) {
  // @@protoc_insertion_point(field_mutable:common.ModulesConfig.modules)
  return modules_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::common::ModuleConfig >*
ModulesConfig::mutable_modules() {
  // @@protoc_insertion_point(field_mutable_list:common.ModulesConfig.modules)
  return &modules_;
}
inline const ::common::ModuleConfig& ModulesConfig::modules(int index) const {
  // @@protoc_insertion_point(field_get:common.ModulesConfig.modules)
  return modules_.Get(index);
}
inline ::common::ModuleConfig* ModulesConfig::add_modules() {
  // @@protoc_insertion_point(field_add:common.ModulesConfig.modules)
  return modules_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::common::ModuleConfig >&
ModulesConfig::modules() const {
  // @@protoc_insertion_point(field_list:common.ModulesConfig.modules)
  return modules_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace common

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_AlgorithmConfig_5fconf_2eproto
