// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TestConfig_conf.proto

#ifndef PROTOBUF_INCLUDED_TestConfig_5fconf_2eproto
#define PROTOBUF_INCLUDED_TestConfig_5fconf_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_TestConfig_5fconf_2eproto 

namespace protobuf_TestConfig_5fconf_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_TestConfig_5fconf_2eproto
namespace test {
class TestConfig;
class TestConfigDefaultTypeInternal;
extern TestConfigDefaultTypeInternal _TestConfig_default_instance_;
}  // namespace test
namespace google {
namespace protobuf {
template<> ::test::TestConfig* Arena::CreateMaybeMessage<::test::TestConfig>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace test {

// ===================================================================

class TestConfig : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:test.TestConfig) */ {
 public:
  TestConfig();
  virtual ~TestConfig();

  TestConfig(const TestConfig& from);

  inline TestConfig& operator=(const TestConfig& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  TestConfig(TestConfig&& from) noexcept
    : TestConfig() {
    *this = ::std::move(from);
  }

  inline TestConfig& operator=(TestConfig&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const TestConfig& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TestConfig* internal_default_instance() {
    return reinterpret_cast<const TestConfig*>(
               &_TestConfig_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(TestConfig* other);
  friend void swap(TestConfig& a, TestConfig& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline TestConfig* New() const final {
    return CreateMaybeMessage<TestConfig>(NULL);
  }

  TestConfig* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<TestConfig>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const TestConfig& from);
  void MergeFrom(const TestConfig& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TestConfig* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string task = 1;
  void clear_task();
  static const int kTaskFieldNumber = 1;
  const ::std::string& task() const;
  void set_task(const ::std::string& value);
  #if LANG_CXX11
  void set_task(::std::string&& value);
  #endif
  void set_task(const char* value);
  void set_task(const char* value, size_t size);
  ::std::string* mutable_task();
  ::std::string* release_task();
  void set_allocated_task(::std::string* task);

  // @@protoc_insertion_point(class_scope:test.TestConfig)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr task_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_TestConfig_5fconf_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TestConfig

// string task = 1;
inline void TestConfig::clear_task() {
  task_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& TestConfig::task() const {
  // @@protoc_insertion_point(field_get:test.TestConfig.task)
  return task_.GetNoArena();
}
inline void TestConfig::set_task(const ::std::string& value) {
  
  task_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:test.TestConfig.task)
}
#if LANG_CXX11
inline void TestConfig::set_task(::std::string&& value) {
  
  task_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:test.TestConfig.task)
}
#endif
inline void TestConfig::set_task(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  task_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:test.TestConfig.task)
}
inline void TestConfig::set_task(const char* value, size_t size) {
  
  task_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:test.TestConfig.task)
}
inline ::std::string* TestConfig::mutable_task() {
  
  // @@protoc_insertion_point(field_mutable:test.TestConfig.task)
  return task_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* TestConfig::release_task() {
  // @@protoc_insertion_point(field_release:test.TestConfig.task)
  
  return task_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void TestConfig::set_allocated_task(::std::string* task) {
  if (task != NULL) {
    
  } else {
    
  }
  task_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), task);
  // @@protoc_insertion_point(field_set_allocated:test.TestConfig.task)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace test

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_TestConfig_5fconf_2eproto
